booklore-app/booklore

booklore-ui/src/environments/environment.prod.ts
Changed the "http:" to ${window.location.protocol} to account for reverse proxies using https.
Expected to fix
- https://github.com/adityachandelgit/BookLore/issues/17
- https://github.com/adityachandelgit/BookLore/issues/18
=> Fixed BASE_URL protocol (for proxy support) in environment.prod.ts

booklore-api/src/main/java/com/adityachandel/booklore/config/AppProperties.java, booklore-api/src/main/java/com/adityachandel/booklore/service/FileUploadService.java, booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/FileProcessingUtils.java, booklore-api/src/main/resources/application.yaml
While trying to setup a dev environment on my main PC (Windows), I met with an error.
The error comes from Tomcat or even JDK implementation, because they handle `transferTo(File)` and `transferTo(Path)` differently. In the project, you use the Path more often and resolve its child (e.g. in `PathService`). But here in `FileUploadService`, `transferTo(File)` was used.
Some examples:
`storagePath` is equal to: \forks\BookLore\local\booktitle.epub
`storageFile` is equal to the same, but on `transferTo(storageFile)`, I received
```logs
2025-04-19T17:43:20.998+02:00 ERROR 36180 --- [booklore-api] [nio-8080-exec-6] c.a.booklore.service.FileUploadService   : Error saving file
java.io.IOException: java.io.FileNotFoundException: C:\Users\astappiev\AppData\Local\Temp\tomcat.8080.6568768355172360310\ …
```
=> fix: uploading books on Windows (dev env) doesn't work

README.md, booklore-api/src/main/resources/application.yaml, example-docker/.env, example-docker/docker-compose.yml
With these changes, we will be able to modify host, port, database name (as well as the whole url), username and password individually.
This is required for the following scenarios (and more):
- using a shared database for multiple services (with a separate username)
- separate root and per-application account, giving an app root permission is not a recommended approach
- port forwarding from e.g. homelab to localhost (e.g. for debugging)
- use MySQL instead of MariaDB (for whatever reason)
Also, this PR:
- removes deprecation warning (Hibernate now automatically detects dialect)
- keeps backwards compatibility using `DB_HOST` and `MYSQL_ROOT_PASSWORD` variable
=> feat: allow modifying mariadb connection

Dockerfile, README.md, booklore-api/src/main/java/com/adityachandel/booklore/config/AppProperties.java, booklore-api/src/main/java/com/adityachandel/booklore/config/security/AuthenticationService.java, booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java, booklore-api/src/main/java/com/adityachandel/booklore/controller/AuthenticationController.java, booklore-api/src/main/java/com/adityachandel/booklore/exception/ApiError.java, booklore-api/src/main/java/com/adityachandel/booklore/service/user/UserCreatorService.java, booklore-api/src/main/resources/application.yaml, booklore-ui/src/app/core/component/login/login.component.ts, booklore-ui/src/app/core/service/auth.service.ts
I have started an attempt to implemented OIDC, as I previously raised in https://github.com/adityachandelgit/BookLore/issues/77.
But was unable to make both, OIDC and simple username/password auths work together.
Therefore, today I decided to abandon the idea and implement MVP solution.
In this PR, I'm suggesting adding a Remote-User auth (requires booklore is running behind a reverse proxy).
This will work with the following setups:
https://doc.traefik.io/traefik/middlewares/http/forwardauth/
https://caddyserver.com/docs/caddyfile/directives/forward_auth
https://www.authelia.com/integration/trusted-header-sso/introduction/
What do you think?
=> feat: add Remote-User auth (alt names ForwardAuth, Trusted Header SSO)

booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.html, booklore-ui/src/app/book/components/epub-viewer/component/epub-viewer.component.ts
Add infinite scroll on the epub reader in the mobile view so that its easier to read.
Before:
The next page arrow interferes with the content on the page
Now: 
smooth scrolling across the book.
=> Add infinite scroll on epub reader in mobile view

booklore-api/src/main/java/com/adityachandel/booklore/config/security/SecurityConfig.java
MoonReader doesn't authenticate when making the GET request to get the search description
As this endpoint doesn't give out any library information , we can allow this endpoint without authenication.
=> [OPDS] Fix search option not recognized by MoonReader

booklore-ui/src/app/book/components/book-browser/book-browser.component.ts, booklore-ui/src/app/book/components/book-browser/cover-scale-preference.service.ts, booklore-ui/src/app/core/service/local-storage-service.ts, booklore-ui/src/app/settings/global-preferences/global-preferences.component.ts
- Store cover scale preference locally to allow different settings per device (desktop, mobile)
- Disabled backend saving for cover scale but kept code commented for future reference
- Load scale preference from LocalStorage on init for faster and device-specific UX
=> Persist cover scale preference per device using LocalStorage

booklore-api/src/main/java/com/adityachandel/booklore/service/bookdrop/BookDropService.java, booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/BookFileProcessor.java, booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/BookFileProcessorRegistry.java, booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/CbxProcessor.java, booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/EpubProcessor.java, booklore-api/src/main/java/com/adityachandel/booklore/service/fileprocessor/PdfProcessor.java, booklore-api/src/main/java/com/adityachandel/booklore/service/library/FileAsBookProcessor.java, booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryFileProcessor.java, booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryFileProcessorRegistry.java, booklore-api/src/main/java/com/adityachandel/booklore/service/library/LibraryProcessingService.java, booklore-api/src/main/java/com/adityachandel/booklore/service/metadata/BookMetadataService.java, booklore-api/src/main/java/com/adityachandel/booklore/service/upload/FileUploadService.java, booklore-api/src/main/java/com/adityachandel/booklore/service/watcher/BookFileTransactionalHandler.java, booklore-api/src/test/java/com/adityachandel/booklore/service/BookDropServiceTest.java, booklore-api/src/test/java/com/adityachandel/booklore/service/library/FileAsBookProcessorTest.java
> [!WARNING]
>
> I can't change base branch to `feature/file-processing-refactoring` branch from my fork.
> In result PR has changes from both branches. It will be fixed when #751 will be merged
This PR introduces a registry-based architecture for book file processing, building upon the refactoring work from the previous [PR](#751). This enhancement creates a flexible foundation for supporting multiple library scan modes and book file formats, addressing the extensibility requirements for future features.
This is the second PR in the series, following the interface consolidation work in `feature/file-processing-refactoring`. The changes in this PR establish the architectural pattern that will enable more sophisticated library processing capabilities.
I've introduced …
=> Registry-based Architecture for Multiple Book Processing Modes

booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html, booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.scss
Currently the checkbox is hard to hit if the series count is visible. Further more, the title is cut so it's impossible to tell what is what. 
This PR will:
- move the series count overlay to the left side of the card
- align the count overlay to the checkbox
- move the series number to bottom
- add the title as a tooltip.
=> feat: move the series count overlay & add title tooltip

booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.html, booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts, booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.html, booklore-ui/src/app/book/components/book-browser/book-table/book-table.component.ts, booklore-ui/src/app/book/components/book-card-lite/book-card-lite-component.html, booklore-ui/src/app/book/components/book-card-lite/book-card-lite-component.ts
this will add tooltips on:
- library book thumbnails
- library table cells
- thumbnail buttons (info & read)
- `similar books`
=> feature: add tooltips on book titles

example-docker/docker-compose.yml
The Docker image was moved to a new repository on Docker Hub, so this must be reflected in the docker-compose.yml example file
=> Update docker-compose.yml example file to the new booklore Docker Hub image identifier

booklore-ui/src/app/bookdrop/bookdrop-file-review-component/bookdrop-file-review.component.ts, booklore-ui/src/app/utilities/component/book-uploader/book-uploader.component.ts
There are some cases where the UI requires extra steps: whenever you have to pick the library & path, even if you only have one option available. With this patch, I want to change this, so if you only have one option, that will automagically selected.
_(i'm still not sure if the first option should be selected even if there are more than one items, suggestions?)_
There are multiple components that implements this, so it will take a bit to deal with all.
- ❓ somewhere else?
=> Feat: automatically set library/path if there is only one option available

CONTRIBUTING.md, booklore-ui/package.json, dev.docker-compose.yml
No need to install java, node and all stuff locally, just run `docker compose -f dev.docker-compose.yml up` and you're good to go.
You can customize exposed ports by adding an `.env` file with `BACKEND_PORT` & `FRONTEND_PORT` value set (defaults are 8080 & 4200).
=> feat: Add docker compose to quickly run a dev env

.github/workflows/docker-build-publish.yml, Dockerfile
Fix GitHub Actions failures after introducing [`Testcontainers`](https://testcontainers.com/)
After merging #868, #870, and #872, repository tests now use `Testcontainers`.
GitHub Actions started failing because the workflow runs docker build, which executes tests during the build step.
Running Docker-in-Docker is required for that pattern, but it is not recommended (and effectively unsupported) with `buildx`.
Solution:
- Run tests directly in the GitHub Actions job (outside docker build).
- Publish test results to GitHub Actions. Example run: https://github.com/werwolfby/BookLore/actions/runs/17283694647/job/49056789485
> [!WARNING]
>
> Replaced hard-coded Docker repository tags with values derived from `github.actor` and `DOCKER_USERNAME`.
> This enables testing the workflow in personal …
=> Fix docker build tests

.github/workflows/docker-build-publish.yml
In #1005 I made an assumption that variables were right (which I specified in warning section).
But assumption was wrong. So I can't test this PR on my personal fork (which this names were intendent to solve).
Just revert names usage to original `booklore` and `booklore-app` values.
P.S. I will check the documentation, probably I could find something like organization name for `booklore-app` and GH registry. And `booklore` could be moved to variables.
@adityachandelgit any thoughts?
Anyway this PR should finally fix the GHA.
=> Fix GHA: return original names for docker tags

booklore-api/src/main/java/com/adityachandel/booklore/controller/KoreaderController.java, booklore-api/src/test/java/com/adityachandel/booklore/controller/KoreaderControllerTest.java
Add content-type header for koreader-sync server in auth method. Needed for some koreader clients (tested in readest iOS app).
fixes https://github.com/booklore-app/booklore/issues/998
=> fix: add content-type header for koreader-sync auth 

booklore-api/src/main/java/com/adityachandel/booklore/service/AdditionalFileService.java, booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java, booklore-api/src/main/java/com/adityachandel/booklore/service/bookdrop/BookDropService.java, booklore-api/src/main/java/com/adityachandel/booklore/service/file/FileMoveService.java, booklore-api/src/main/java/com/adityachandel/booklore/service/monitoring/MonitoringProtectionService.java, booklore-api/src/test/java/com/adityachandel/booklore/BookServiceDeleteTests.java, booklore-api/src/test/java/com/adityachandel/booklore/FileMoveServiceMoveFilesTest.java, booklore-api/src/test/java/com/adityachandel/booklore/service/AdditionalFileServiceTest.java, booklore-api/src/test/java/com/adityachandel/booklore/service/BookServiceDeleteBooksTest.java, booklore-api/src/test/java/com/adityachandel/booklore/service/MonitoringProtectionConcurrentTest.java, booklore-api/src/test/java/com/adityachandel/booklore/service/MonitoringProtectionIntegrationTest.java, booklore-api/src/test/java/com/adityachandel/booklore/service/MonitoringProtectionRaceConditionTest.java
- Implement `MonitoringProtectionService` with thread-safe pause/resume logic
- Add monitoring protection to file operations preventing data loss from race conditions
- Add comprehensive test coverage including concurrent and integration tests
Race condition scenario: File operations (move/delete) detected as "missing files" by monitoring system before filesystem operations complete, causing incorrect book removal and data loss.
Solution: Thread-safe monitoring pause during file operations with delayed resume to ensure filesystem operations complete before monitoring resumes.
I don't know for certain which of these are fixed but it's an attempt at: #958, #846, #951, #972, #894 and maybe some others.
=> feat: Add comprehensive race condition prevention for file operations

booklore-ui/src/app/book/components/book-browser/book-card/book-card.component.ts, booklore-ui/src/app/metadata/book-metadata-center-component/metadata-viewer/metadata-viewer.component.ts
Encode the series name in the URL to handle special characters (e.g., %). Without encoding, decodeURIComponent in the route crashes when such characters are present.
Linked issue: #1175
Video after fixes: 
https://github.com/user-attachments/assets/a4c77878-0a48-48b0-a946-887b6148e9a5
=> Fix: encode URI params for series names with special characters

booklore-api/src/main/java/com/adityachandel/booklore/mapper/ShelfMapper.java, booklore-api/src/main/java/com/adityachandel/booklore/mapper/v2/BookMapperV2.java, booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
Fix for #978 
It might make sense to filter the shelves in the book mapper itself so it happens on every use of `toBook`. But given that it's used in a lot of places and I'm not familiar with most of the project's code I'm afraid that could introduce some issue I'm unaware of. So I filtered the resulting shelves specifically in the method needed to fix the existing issue.
I tested it locally with the same setup of users and books with which I could reproduce the error and this fixes it.
=> fix: stop sending shelves not associated with the user

booklore-api/src/main/java/com/adityachandel/booklore/service/BookService.java
This small PR is my attempt at setting the read status for a book based on the KoReader Sync plugin. While I am fairly new to Java dev, and therefore currently not set up to test this locally, I assume this should work, but changes are welcome. 
This was created in reference to [this discord feature request](https://discord.com/channels/1379932933581963444/1379934554957152336/1424024474898141255)
I'm not sure if this can be applied to the other types as well, I only have epubs in my library and therefore only added the part to  the epub area
Feedback / Suggestions are welcome
=> Feat: set reading status using Koreader Sync Plugin
